name: Aquaman
main: MulqiGaming64\Aquaman\Aquaman
version: 1.0.0
api: 4.0.0
description: now you can breathe in water without limit
author: MulqiGaming64

permissions:
 aquaman.transform:
  default: op
  description: Transform Into Aquaman
